# Generated by Django 3.1.1 on 2020-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commentblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpName', models.CharField(max_length=20)),
                ('helpText', models.TextField()),
            ],
        ),
    ]
